# Importing libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import tensorflow as tf

In [11]:
images_folder = os.path.join("data", "animals", "animals")
# List all animal categories
animal_categories = os.listdir(images_folder)
# Access a specific animal folder
first_animal = animal_categories[0] 
first_animal_path = os.path.join(images_folder, first_animal)
first_animal_images = os.listdir(first_animal_path)
# To iterate through all animals and their images
animal_stats = {}
for animal in animal_categories:
    animal_path = os.path.join(images_folder, animal)
    images = os.listdir(animal_path)
    animal_stats[animal] = len(images)

# Print animals with most and least images
sorted_stats = sorted(animal_stats.items(), key=lambda x: x[1])

In [32]:
# convert txt to csv
animal_names = os.path.join("data", "animals.txt")
animal_names = pd.read_csv(animal_names)
# save as csv
animal_names.to_csv("data/animal_names.csv", index=False)

animal_names.head(20)

       antelope
0        badger
1           bat
2          bear
3           bee
4        beetle
5         bison
6          boar
7     butterfly
8           cat
9   caterpillar
10   chimpanzee
11    cockroach
12          cow
13       coyote
14         crab
15         crow
16         deer
17          dog
18      dolphin
19       donkey

In [39]:
# Creating a dataframe for animal images and seeing if they are in the csv
# Convert animal categories to DataFrame for easier comparison
df_animal_categories = pd.DataFrame(animal_categories, columns=["Animal Name"])

# Create empty dataframe for results
my_df = pd.DataFrame(columns=["Images Folder", "Animal Name"])

# Add each animal to the dataframe 
for animal in animal_categories:
    new_row = pd.DataFrame({"Images Folder": [animal], "Animal Name": [animal]})
    my_df = pd.concat([my_df, new_row], ignore_index=True)

my_df.head(20)

   Images Folder   Animal Name
0   hippopotamus  hippopotamus
1        sparrow       sparrow
2        gorilla       gorilla
3            cat           cat
4     rhinoceros    rhinoceros
5         wombat        wombat
6       seahorse      seahorse
7      butterfly     butterfly
8         donkey        donkey
9        raccoon       raccoon
10     dragonfly     dragonfly
11          crab          crab
12           pig           pig
13     orangutan     orangutan
14        turtle        turtle
15      antelope      antelope
16           dog           dog
17           bee           bee
18        coyote        coyote
19           fox           fox